### ISSUE TITLE
Невозможно получить ответ при создании комнаты.

### ISSUE THREAD

**Issue by developerdevpav** [VladislavPetyukevich/GulagGazRoom#146]
500
{
  "message": "Internal Server Error."
}

Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles

**Comment by blowin** [comment]
Во время какого запроса ошибка? Видимо рекурсивная ссылка в результате

**Comment by developerdevpav** [comment]
> Во время какого запроса ошибка? Видимо рекурсивная ссылка в результате

Во время создания комнаты возвращается исключение [цекличная сериализация]. Да просто домику не надо пробрасывать.

**Comment by blowin** [comment]
Вообще можно использовать [это](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.referencehandler.ignorecycles?view=net-7.0) при серриализации, чтобы в будущем такого не возникало

**Comment by blowin** [comment]
Нужно проверить, но наверняка этого должно быть достаточно

![image](https://user-images.githubusercontent.com/22686801/230724485-73485965-c18e-4082-bd9d-c7e440b1a62b.png)

**Comment by developerdevpav** [comment]
Да, классно что не надо вешать на room аннотации. И да, в любом случае нужно переписывать на ДТО.
