### ISSUE TITLE
Система владения ресурсами

### ISSUE THREAD

**Issue by VladislavPetyukevich** [VladislavPetyukevich/GulagGazRoom#198]
Главная ценность - дать всем пользователям возможность создавать свои ресурсы (комнаты, вопросы, отзывы) и управлять ими.

**Comment by developerdevpav** [comment]
https://www.notion.so/developerdevpav/58dfd0f57c7f4ffa8638670a19b77a54?pvs=4

**Comment by VladislavPetyukevich** [comment]
УРА! УРА! УРА!
