### ISSUE TITLE
Универсализировать систему событий

### ISSUE THREAD

**Issue by VladislavPetyukevich** [VladislavPetyukevich/GulagGazRoom#200]
Предполагается, что доступные реакции будут храниться в таблице.

**Comment by blowin** [comment]
Решили добавить таблицу с состоянием комнаты, структура примерно такая

{
   roomId: Guid NOT NULL
   type: string NOT NULL
   payload: string (JSON) NOT NULL
}

Уникальность в рамках (roomId, type)

**Comment by VladislavPetyukevich** [comment]
Сделано в рамках https://github.com/VladislavPetyukevich/GulagGazRoom/pull/256
