### ISSUE TITLE
Категория вопроса как тэг

### ISSUE THREAD

**Issue by VladislavPetyukevich** [VladislavPetyukevich/GulagGazRoom#207]
Надо создать сущность "тэг вопроса". Естественно она нужна для определения темы или тем вопроса, поэтому надо связать вопрос с его тэгами.

Предполагаемые поля:
- Имя (например, .Net).

**Comment by blowin** [comment]
Добавил новые endpoints для вопроса. Так можно найти тэги, добавить, удалить

![image](https://github.com/VladislavPetyukevich/GulagGazRoom/assets/22686801/e8379694-6931-4df1-8f35-8390f9154c6e)

Также теперь при создании, изменении вопроса, можно связать указать тэг и привязать/удалить.
Если в списке тэгов во время обновления вопроса не будет изменений, то список тегов останется прежник, если добавятся или удалятся какие-то тэги, то это применится в БД.

**Comment by VladislavPetyukevich** [comment]
Нужно пару доработок:

- Исправить то, что в ответе на получение вопроса по id (GET /questions/{id}) всегда приходит пустой массив тэгов;
- В ответе на запрос страницы вопросов (GET /questions) мне удобнее получать массив тэгов объектами с id, чем массив значений тэгов (массив строк).

**Comment by VladislavPetyukevich** [comment]
- Стоит привязывать цвет тэга во время создания тэга, а не во время создания вопроса. А то сейчас получается, что у одного тэга могут быть разные цвета в разных вопросах.
