### ISSUE TITLE
Обработка событий WebSocket для видеочата

### ISSUE THREAD

**Issue by VladislavPetyukevich** [VladislavPetyukevich/GulagGazRoom#219]
Сервер должен обрабатывать  данные события по WebSocket.

Имя события: *join video chat*
Действия:
Запомнить пользователя как участника видеочата. Запоминать надо id пользователя. Отправить этому сокету событие "all users". Полезная нагрузка у "all users" - json массив id всех пользователей видеочата.
 
Имя события: *sending signal*
Полезная нагрузка: JSON объект с полями: to (id пользователя), from (id пользователя), signal
Действия:
Отправить, пользователю с id из поля to, событие "user joined", полезная нагрузка - JSON объект (signal, from).
 
Имя события: *returning signal*
Полезная нагрузка: JSON объект с полями: to (id пользователя), from (id пользователя), signal
Действия:
Отправить, пользователю с id из поля from, событие "receiving returned signal", полезная нагрузка - JSON объект (signal, to).

```
{
  to (id пользователя): guid;
  from (id пользователя): guid;
  signal: строка;
}
```

**Comment by blowin** [comment]
From нам тоже не нужно, у нас есть UserId, который подключился, т.е только To

**Comment by blowin** [comment]
Какое сообщение или ошибка на backend?

**Comment by VladislavPetyukevich** [comment]
> Какое сообщение или ошибка на backend?

В консоли бэка ошибок нет, просто сбрасывается подключение по WS. Если пользователя сделать админом, то такого не происходит.

**Comment by blowin** [comment]
Дело в permissions, у админа есть права на всё, а у других пользователей они должны быть отдельно. а у твоего юзера нет нужных прав и он падает

**Comment by VladislavPetyukevich** [comment]
Нужно в Paload у события _user joined_ добавить инфу о пользователе. Можно в Payload добавить новое поле FromMeta и в нём два поля: _nickname_ и _avatar_

**Comment by blowin** [comment]
Будет следующий paylaod
![image](https://github.com/VladislavPetyukevich/GulagGazRoom/assets/22686801/c4455832-9c6a-4a4b-99f9-14e21ac0bc84)
