### ISSUE TITLE
Хранение состояния комнаты

### ISSUE THREAD

**Issue by blowin** [VladislavPetyukevich/GulagGazRoom#220]
Решили добавить таблицу с состоянием комнаты, структура примерно такая

```
{
   roomId: Guid NOT NULL
   type: string NOT NULL
   payload: string (JSON) NOT NULL
}
```

Уникальность в рамках (roomId, type)

**Comment by VladislavPetyukevich** [comment]
Решено в рамках https://github.com/VladislavPetyukevich/GulagGazRoom/pull/256
