### ISSUE TITLE
Подключить Redis к Backend

### ISSUE THREAD

**Issue by blowin** [VladislavPetyukevich/GulagGazRoom#241]

**Comment by VladislavPetyukevich** [comment]
Комментарии из обсуждения: определиться с реализацией, лучшим индексом, перевод в холодное хранилище, очищение данных). Сохранение событий чата

**Comment by blowin** [comment]
При отправке событий видео чата, вместо поля Payload нужно отправлять свойство Value. Также теперь при получении события будет так же получен Id + CreatedAt + Stateful + Value (вместо Payload)

**Comment by VladislavPetyukevich** [comment]
Сейчас бэк не реагирует на события видеочата. При входе в видеочат, с фронта по прежнему отправляется `{Type: "join video chat"}`. В ответ не приходит список участников видеочата. И другим пользователям не приходят события о подключение нового пользователя

**Comment by blowin** [comment]
В каком виде отправляется событие?
Попробовал сделать локально без redis
![image](https://github.com/VladislavPetyukevich/GulagGazRoom/assets/22686801/d1613294-f42c-4f5b-8656-1e1ec215ec4f)
![image](https://github.com/VladislavPetyukevich/GulagGazRoom/assets/22686801/774aad74-dd8b-4f06-9066-72825e6a4ab3)
