### ISSUE TITLE
Система аутентификации 

### ISSUE THREAD

**Issue by VladislavPetyukevich** [VladislavPetyukevich/GulagGazRoom#37]
Основная проблема в том, что пользователь может логиниться как с фронта собеседуемого так и с фронта админ-панели. Т. е. нужен редирект в разные места.

Предлагаю такую схему работы:
1. Я направляю пользователя на User/GetMe?**redirectUrl**=...;
2. User/GetMe делает всю аутентификацию на twitch;
3. После аутентификации в twitch, идёт редирект обратно на User/GetMe, но он уже отвечает редиректом 302 на указанный мной **redirectUrl** (тут нужен список разрешённых **redirectUrl**) и ~~заголовком set-cookie с нужным cookie~~ (всё будет на одном домене).

Если нереально запомнить **redirectUrl** в такой схеме, то можно сделать немного по-другому. Можно использовать разные руты для авторизации с фронта собеседуемого (**User/GetMe/Interviewee**) и с фронта админ-панели (**User/GetMe/Admin**).

**Comment by developerdevpav** [comment]
На backend нужно реализовать следующее:

- [ ] Любой запрос на защищенный ресурс (без cookie) должен возвращать HttpStatus 401

- [ ] Любой запрос на защищенный ресурс (с cookie но без прав) должен возвращать HttpStatus 403

- [ ] Создать открытый endpoint для авторизации в Twitch.
