### ISSUE TITLE
Нет возможности отправлять заголовок Authorization при подключении к WebSocket

### ISSUE THREAD

**Issue by VladislavPetyukevich** [VladislavPetyukevich/GulagGazRoom#38]
В браузерном WebSocket нет возможности отправлять свои заголовки при подключении: https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api
Так же, нет возможности отправлять тело запроса.
Как альтернатива, можно отправлять Authorization в параметрах url для подключения.

**Comment by developerdevpav** [comment]
Тело запроса отправляется уже после подключения в websocket.
Можем изменить отправку Authorization в параметрах URL. если есть такая возможность то может и id комнаты сразу отправить.

**Comment by VladislavPetyukevich** [comment]
Да, могу сразу отправить Authorization и id комнаты

**Comment by developerdevpav** [comment]
feature/#38 ветка.
query
Authorization 
roomId
