### ISSUE TITLE
Привязывать реакции к таблице связки [комната, вопрос]

### ISSUE THREAD

**Issue by developerdevpav** [VladislavPetyukevich/GulagGazRoom#43]
Привязывать реакции к таблице связки [комната, вопрос]

Таким образом мы сможем понять какие реакции были на конкретный вопрос в комнате.

```
RoomQuestion table
{
   Id
   RoomId,
   QuestionId
   Status [Closed, Open, Active]
}
```

```
RoomQuestionReaction table
{
  Id
  ReactionId
  RoomQuestionId
  FromUserId
}
```

```
Reaction table
{
   Id
   Type
}
```

Необходимые endpoints:
- POST: api/Reaction/Create (в базе на backend'е мы ищем текущий вопрос в комнате и вставляем базу информацию вместе с текущим вопросом) + push event to websocket
```
{
   Type
   RoomId
}

response: ok/not ok
```
- POST: api/Room/ChangeActiveQuestion (если такого вопроса нет в комнате/или он уже активный - bad request, иначе делаем этот вопрос активный, а предыдущий активный закрываем) + push event to websocket
```
{
  RoomId
  QuestionId - новый активный вопрос
}

response: ok/not ok
```

**Comment by blowin** [comment]
Как я понимаю у нас будет либо QuestionId = id вопроса, либо null, если реакция не для вопроса или предлагаешь делать отдельную таблицу?(мне кажется не стоит)

**Comment by developerdevpav** [comment]
> 

Нет. В комнате вопрос не может быть null. 
Реакция - реакция пользователей на текущий вопрос. 

Мы можем потом разграничить по логике к чему реакция приписывается.

**Comment by developerdevpav** [comment]
реакция будет добавляться так:
Реакции - обычный справочник.

{
roomId: "",
questionId: "",
reactionId: ""
}
