### ISSUE TITLE
Добавить подключение к чату пользователя для чтения событий

### ISSUE THREAD

**Issue by developerdevpav** [VladislavPetyukevich/GulagGazRoom#71]

**Comment by VladislavPetyukevich** [comment]
Чтение чата должно запускаться при подключении первого клиента в комнату по websocket.
Чтение чата должно останавливаться при отключении последнего клиента из комнаты websocket.

**Comment by VladislavPetyukevich** [comment]
Пока клиент твич лежит тут (TwitchChatClient.cs): https://github.com/VladislavPetyukevich/GulagGazRoom/commit/8fb032a5369853f2fe87050a43d103217db669f9#diff-06a7799a7079fdb0ac2e1be42838402bba8d7272779f1f4882f310f8891d7d36
